### ISSUE TITLE
32 Bit Notice From Bakkes

### ISSUE THREAD

**Issue by wild-wild-smif** [CinderBlocc/SpectateCameraShortcuts#1]
According to BakkesPlugins:

“BakkesMod has dropped support for 32bit plugins. This plugin has not yet been updated to 64bit. Until the plugin has been recompiled by the author, downloads are unavailable”

Thought I'd give you a heads-up.

**Comment by deveron3** [comment]
Here's the link:
https://bakkesplugins.com/plugins/view/49

**Comment by CinderBlocc** [comment]
Thanks for the heads up! I plan on having all my plugins updated by the end of the week.

**Comment by wild-wild-smif** [comment]
Eyyy, it's back up! Thanks Cinder <3
